### ISSUE TITLE
Containerized OpenstackCLI -> vexxhost.atmosphere.barbican : Add implied roles

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#1186]
At the tasks `vexxhost.atmosphere.barbican : Add implied roles` I get the following error:
```
TASK [vexxhost.atmosphere.barbican : Add implied roles] ************************
failed: [ctl1] (item={'role': 'member', 'implies': 'creator'}) => {"ansible_loop_var": "item", "changed": false, "cmd": "set -o posix\nsource /etc/profile.d/atmosphere.sh\nopenstack implied role create  --implied-role creator  member\n", "delta": "0:00:00.005725", "end": "2024-05-04 22:59:24.553232", "failed_when_result": true, "item": {"implies": "creator", "role": "member"}, "msg": "non-zero return code", "rc": 1, "start": "2024-05-04 22:59:24.547507", "stderr": "/bin/bash: -c: line 5: syntax error near unexpected token `('\n/bin/bash: -c: line 5: `nerdctl run --rm --network host \\\n      --volume $PWD:/opt --volume /tmp:/tmp \\\n      --volume /etc/openstack:/etc/openstack:ro \\\n      --env-file <(env | grep OS_) \\\n      cluster6.DOMAIN.TLD/openstack-helm/infra/python-openstackclient:zed'", "stderr_lines": ["/bin/bash: -c: line 5: syntax error near unexpected token `('", "/bin/bash: -c: line 5: `nerdctl run --rm --network host \\", "      --volume $PWD:/opt --volume /tmp:/tmp \\", "      --volume /etc/openstack:/etc/openstack:ro \\", "      --env-file <(env | grep OS_) \\", "      cluster6.DOMAIN.TLD/openstack-helm/infra/python-openstackclient:zed'"], "stdout": "", "stdout_lines": []}
```

Probably this is because this gets sourced and in the alias profile file does not like the < sign

**Comment by mnaser** [comment]
@mpiscaer I'm curious how this is currently working in CI.  Do you know if this is something different at your side?

**Comment by mpiscaer** [comment]
I was wondering that too why it did not popup before in the CI. I could not find anything on my side.

**Comment by mpiscaer** [comment]
@mnaser If I look in to the checks of PR #972 -> https://github.com/vexxhost/atmosphere/pull/972/checks?check_run_id=24443230718

I see that I run the following checks:
```
✔️ atmosphere-buildset-registry SUCCESS in 3m 06s
✔️ atmosphere-build-container-image-python-openstackclient SUCCESS in 6m 41s
✔️ atmosphere-linters SUCCESS in 3m 57s
✔️ atmosphere-build-collection SUCCESS in 3m 26s
✔️ atmosphere-molecule-aio-keycloak SUCCESS in 19m 48s
✔️ atmosphere-molecule-aio-openvswitch SUCCESS in 1h 32m 43s
❌ atmosphere-molecule-aio-ovn FAILURE in 1h 34m 17s (non-voting)
✔️ atmosphere-molecule-csi-local-path-provisioner SUCCESS in 8m 40s
✔️ atmosphere-molecule-csi-rbd SUCCESS in 19m 42s
```

None of them check the barbican role.

Also when I look into the logs from for example [atmosphere-molecule-aio-keycloak](https://logs.atmosphere.dev/72/972/97f1edb088a0bb59f0530aade7b56f4d47c440b7/check/atmosphere-molecule-aio-keycloak/6df52d0/job-output.txt) I don't see any tasks called 'Add implied roles'.

**Comment by mpiscaer** [comment]
I see couple of solutions that are possible:
1. Use a direct command without alias
```
    ansible.builtin.shell:
      cmd: |
        nerdctl run --rm --network host --volume $PWD:/opt --volume /tmp:/tmp --volume /etc/openstack:/etc/openstack:ro --env-file <(env | grep OS_) cluster1.gitlab-runner.ci.cloud.c3.cgm.ag/openstack-helm/infra/python-openstackclient:main \
        openstack --insecure implied role create \
          --implied-role {{ item.implies }} \
          {{ item.role }}
      executable: /bin/bash
    loop:
      - role: member
        implies: load-balancer_member
      - role: reader
        implies: load-balancer_observer
    environment:
      OS_CLOUD: atmosphere
    register: _octavia_implied_role_create
    changed_when: _octavia_implied_role_create.rc == 0
    failed_when: _octavia_implied_role_create.rc != 0 and 'Duplicate entry.' not in _octavia_implied_role_create.stderr
```

2. Use a shell script instead of alias, for example a shell script located in /usr/local/bin/openstack
3. use a function instead of alias

About the solution for alias of function, I don't know if the directory /etc/profile.d is very ubuntu specific and how many other distros uses this.
