### ISSUE TITLE
Configure scheduler to support host aggregates

### ISSUE THREAD

**Issue by KeplerSysAdmin** [vexxhost/atmosphere#1283]
To configure the scheduler for host aggregates, add AggregateInstanceExtraSpecsFilter to the enabled_filters option in nova.conf. This allows you to schedule instances to specific compute hosts with capabilities like SSDs or GPUs.

Example:
```
[filter_scheduler]
enabled_filters=...,AggregateInstanceExtraSpecsFilter
```

1. Does atmosphere support this feature by default?, because we have to enable it on our second environment
2. We added the feature using the following YAML:

```
---
_nova_enabled_filters: "AvailabilityZoneFilter, ComputeFilter, AggregateTypeAffinityFilter, ComputeCapabilitiesFilter, PciPassthroughFilter, ImagePropertiesFilter, ServerGroupAntiAffinityFilter, ServerGroupAffinityFilter, AggregateInstanceExtraSpecsFilter"

nova_helm_values:
  conf:
    nova:
      filter_scheduler:
        enabled_filters: "{{ _nova_enabled_filters }}"
```
