### ISSUE TITLE
ovn: oci_image_registry secret uses chart name

### ISSUE THREAD

**Issue by gtirloni** [vexxhost/atmosphere#1336]
Atmosphere's ovn chart v0.1.4 has this in [values.yaml](https://github.com/vexxhost/atmosphere/blob/main/charts/ovn/values.yaml#L252-L258):

```yaml
secrets:
  oci_image_registry:
    ovn_ovsdb_nb: ovn-ovsdb-nb-oci-image-registry-key
    ovn_ovsdb_sb: ovn-ovsdb-sb-oci-image-registry-key
    ovn_northd: ovn-northd-oci-image-registry-key
    ovn_controller: ovn-controller-oci-image-registry-key
    ovn_controller_gw: ovn-controller-gw-oci-image-registry-key
```

However, the [helm-toolkit](https://github.com/vexxhost/atmosphere/blob/main/charts/ovn/charts/helm-toolkit/templates/snippets/_kubernetes_pod_rbac_serviceaccount.tpl#L48) template indexes into `oci_image_registry` using `.Chart.Name` and not `$serviceName`:

```yaml
{{- if $envAll.Values.endpoints.oci_image_registry.auth.enabled }}
imagePullSecrets:
  - name: {{ index $envAll.Values.secrets.oci_image_registry $envAll.Chart.Name }}
{{- end -}}
```

So to specify the secret to be used (either pre-existing or to be created if `manifest.secret_registry: true`), it's enough to specify the chart name only:

```yaml
secrets:
  oci_image_registry:
   ovn: ovn-oci-image-registry-key
```

Issue also present in upstream ovn chart v0.1.10
