### ISSUE TITLE
When running only openstack playbook, no facts gathered

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#186]
When only running vexxhost.atmosphere.openstack no "Gathering Facts" gets done, this results that task [Set binding for ports](https://github.com/vexxhost/atmosphere/blob/main/roles/openstack_helm_octavia/tasks/main.yml#L68-L76) fails with the error that "has no attribute 'ansible_fqdn'".

**Comment by mnaser** [comment]
ahh, this was done to prevent unnecessary work to be done.  I've got an idea how we can work around this.

**Comment by runlevel-six** [comment]
We've run into this as well - we get around it by changing `gather_facts` to true on the call to the flux role:

```yaml
- hosts: controllers
  gather_facts: true
  become: true
  roles:
    - role: flux
      tags:
        - flux
```

It is only there until a better solution is available and I chose that role because it gathers facts for all of the controllers which are needed for the port binding you mention.
