### ISSUE TITLE
Missing away to overide settings for Magnum

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#231]
Missing away to overide settings for Magnum.

Like for example the Magnum image. Currently we use our own images where we change a couple of thinks like for example a internal corporate CA.

**Comment by mnaser** [comment]
@mpiscaer this can now be handled with the following:

```
atmosphere_cloud_spec:
  magnum:
    overrides:
      conf:
        magnum:
          foo:bar
```

Pretty much anything inside `overrides` will be applied to the Helm chart values.
