### ISSUE TITLE
[513] Add docs for netapp backend

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/atmosphere#2352]
```
---
cinder_helm_values:
  pod:
    mounts:
      cinder_volume:
        cinder_volume:
          volumeMounts:
            - name: ca-certificates
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
          volumes:
            - name: ca-certificates
              hostPath:
                path: "{{ defaults_ca_certificates_path }}"
    useHostNetwork:
      volume: true
    security_context:
      cinder_volume:
        container:
          cinder_volume:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 0
  storage: netapp
  conf:
    enable_iscsi: true
    cinder:
      DEFAULT:
        enabled_backends: netapp
        default_volume_type: netapp
    backends:
      rbd1: null
      netapp:
        volume_backend_name: netapp
        volume_driver: cinder.volume.drivers.netapp.common.NetAppDriver
        netapp_storage_protocol: iscsi
        netapp_storage_family: ontap_cluster
        netapp_server_hostname: openstacksvm.dataposit.co.ke
        netapp_transport_type: https
        netapp_vserver: openstack_svm
        netapp_login: "{{ netapp_username }}"
        netapp_password: "{{ netapp_password  }}"
        netapp_lun_space_reservation: disabled
        use_multipath_for_image_xfer: True
  manifests:
    deployment_backup: false
    job_backup_storage_init: false
    job_storage_init: false
  dependencies:
    static:
      api:
        jobs:
          - cinder-db-sync
          - cinder-ks-user
          - cinder-ks-endpoints
          - cinder-rabbit-init
      scheduler:
        jobs:
          - cinder-db-sync
          - cinder-ks-user
          - cinder-ks-endpoints
          - cinder-rabbit-init
      volume:
        jobs:
          - cinder-db-sync
          - cinder-ks-user
          - cinder-ks-endpoints
          - cinder-rabbit-init
      volume_usage_audit:
        jobs:
          - cinder-db-sync
          - cinder-ks-user
          - cinder-ks-endpoints
          - cinder-rabbit-init
```
