### ISSUE TITLE
Add secure RBAC for Magnum

### ISSUE THREAD

**Issue by ricolin** [vexxhost/atmosphere#471]
Address the needs for secure RBAC for Magnum to let users aware the possible upcoming changes

https://review.opendev.org/c/openstack/magnum/+/875625/14
https://github.com/vexxhost/magnum/pull/10

**Comment by ricolin** [comment]
We already have rbac released in vexxhost/magnum:zed and have the container tested.
The openstack community patch still requires some fixes before heat drivers are usable, but because we use vexxhost/magnum-cluster-api as driver, it will not be a problem.
it's added in PR: https://github.com/vexxhost/atmosphere/pull/487
What this means is, whoever not using magnum-cluster-api driver (aka not using atmosphere) will not be able to use that vexxhost/magnum:zed image.
For enable magnum rbac
simply add magnum config like follow:
```
conf:
     magnum:
       oslo_policy:
          enforce_new_defaults: True
          enforce_scope: True
```
