### ISSUE TITLE
feature request: automatic secret rotation

### ISSUE THREAD

**Issue by fitbeard** [vexxhost/atmosphere#521]
Right now oslo.config has driver(enabled by default) which allows reading configuration from environment variables:
https://opendev.org/openstack/oslo.config/commit/ea8a0f6a8b260474151fb27c2adc9dcc88774850
https://specs.openstack.org/openstack/oslo-specs/specs/rocky/config-from-environment.html
https://docs.openstack.org/oslo.config/latest/reference/drivers.html
The idea is to use HashiCorp Vault agent (sidecar) for all containers + https://github.com/vexxhost/vault-plugin-secrets-openstack + other Vault secret engines to rotate all secrets via Vault.

**Comment by lukasmrtvy** [comment]
Another use case for Vault related to the secrets would be as a Barbican backend: https://docs.openstack.org/barbican/latest/install/barbican-backend.html#vault-plugin

**Comment by ricolin** [comment]
So right now what make Vault a weird case is it's under Business Source License 1.1 (https://github.com/hashicorp/vault/blob/main/LICENSE#L20) so might not suit production uses and a bit strange to add to Atmosphere.

**Comment by lukasmrtvy** [comment]
https://news.ycombinator.com/item?id=37089944

**Comment by mnaser** [comment]
I spoke with Hashicorp and they are OK with us using Terraform in Atmosphere, but I will need to bring up Vault.

**Comment by fitbeard** [comment]
Hi. I made huge progress on this issue: https://github.com/fitbeard/atmosphere/compare/vault_poc_pre_timestamp...vault_poc. Before pushing I need to figure out how to make changes in helm-toolkit and OS charts to add custom annotations to secrets and how to skip values like region, username, password for service and MQ/DB connection strings.

**Comment by fitbeard** [comment]
Here is example which can be used for init/db-sync-like containers:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tadas-test
  namespace: openstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
        vault.security.banzaicloud.io/vault-role: "vault"
        vault.security.banzaicloud.io/vault-tls-secret: vault-tls
        vault.security.banzaicloud.io/vault-path: "kubernetes"
    spec:
      serviceAccountName: default
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY - $CRED_SECRET && echo going to sleep... && sleep 180"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/demosecret/aws#AWS_SECRET_ACCESS_KEY
        - name: CRED_SECRET
          value: vault:openstack/creds/vault#application_credential_secret

```
