### ISSUE TITLE
os_region_name stick to the old value

### ISSUE THREAD

**Issue by migmeneses** [vexxhost/atmosphere#636]
## Description
We've encountered an issue related to the 'os_region_name' parameter for nova.conf
It is using the default value RegionOne, even when we have specified another value.
This is causing issues during nova API calls finishing in HTTP 500 errors

**Comment by mnaser** [comment]
the fix involved making the following addition:

```yaml
nova_helm_values:
  conf:
    nova:
      cinder:
        os_region_name: "{{ openstack_helm_endpoints['identity']['auth']['nova']['region_name'] }}"
        username: "{{ openstack_helm_endpoints['identity']['auth']['nova']['username'] }}"
        password: "{{ openstack_helm_endpoints['identity']['auth']['nova']['password'] }}"
```

we should make it a default.

**Comment by mpiscaer** [comment]
I also had to set this, in neutron the placement settings where openstack-helm defaults. And the `openstack_helm_endpoints` are not set yet in the group_vars

```
neutron_helm_values:
  conf:
    neutron:
      placement:
        os_region_name: "{{ openstack_helm_endpoints_region_name }}"
        username: "placement-{{ openstack_helm_endpoints_placement_region_name }}"
        password: "{{ openstack_helm_endpoints_placement_keystone_password }}"
```
