### ISSUE TITLE
Error on initial neutron deployment when `openstack_helm_neutron_networks` is populated

### ISSUE THREAD

**Issue by runlevel-six** [vexxhost/atmosphere#69]
On an initial deployment of OpenStack in Atmosphere, if the `openstack_helm_neutron_networks` is left empty, then there is no problem finishing the deployment of the `openstack-helm-neutron` role and the `openstack` playbook continues on to deploy the rest of the stack.

But if `openstack_helm_neutron_networks` is populated, the playbook will fail because the neutron networks cannot be added until an availability zone is created. That happens, as I understand it, in the `openstack-helm-nova` role. So when deploying for the first time with this variable populated, the playbook fails, at which point I re-run the `openstack` playbook with the flag `-t openstack-helm-nova` to only deploy nova. Once that completed, I can re-run the entire `openstack` playbook and everything completed with no errors. 

The only entry in the `openstack_helm_neutron_networks` array I am using is similar to one below:

```yaml
openstack_helm_neutron_networks:
- external: true
  mtu_size: 1500
  name: public
  port_security_enabled: true
  provider_network_type: flat
  provider_physical_network: external
  shared: true
  subnets:
  - allocation_pool_end: 10.1.160.90
    allocation_pool_start: 10.1.160.51
    cidr: 10.1.160.0/24
    dns_nameservers:
    - 1.1.1.1
    - 1.0.0.1
    enable_dhcp: true
    gateway_ip: 10.1.160.1
    name: public-subnet
```
