### ISSUE TITLE
The name of keystone_keycloak_realm_name was not set into Horizon

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#727]
When I change keystone_keycloak_realm_name it never sets it to Horizon. it only uses the undefined value.

When I set 

```YAML
horizon_helm_values:
  conf:
    horizon:
      local_settings:
          auth:
            idp_mapping: "{{ keystone_domains | default([{'name': 'atmosphere', 'label': 'MyOwn SSO'}]) | vexxhost.atmosphere.keystone_domains_to_idp_mappings }}" # noqa: yaml[line-length]
```

I get the correct name.
