### ISSUE TITLE
bug: keystone task to validate if ingress is reachable is failing

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/atmosphere#764]
## Problem
This task(keystone role) is failing because the keystone is not reachable even after all retries.
```yaml
- name: Validate if ingress is reachable
  ansible.builtin.uri:
    url: "https://{{ openstack_helm_endpoints_keystone_api_host }}"
    status_code: [300]
  register: keystone_ingress_validate
  until: keystone_ingress_validate.status == 300
  retries: 60
  delay: 1
```
## Reason
It takes a bit long time for Atmosphere certificate to be issued. Retries is not long enough to wait till the cert is issued.

## Fix/solution
Add a task to wait the cert issue explicitly instead of increasing the retries in ingress validation task. Because the retries in the ingress validation task is for keystone bootstrap itself, not for cert.
